version: '2.4'

networks:
  extranet:
    name: dath-extranet
    ipam:
      config:
        - subnet: '10.10.0.0/16'
          gateway: '10.10.163.1'

  dmz:
    name: dath-dmz
    ipam:
      config:
        - subnet: '172.16.163.0/24'
          gateway: '172.16.163.1'

  intranet:
    name: dath-intranet
    ipam:
      config:
        - subnet: '192.168.163.0/24'
          gateway: '192.168.163.1'

services:
  #########################################
  #                Bastion                #
  #########################################
  bastion:
    build: ./hosts/bastion
    image: dath/bastion:latest
    restart: always
    container_name: dath-bastion
    cap_add:
      - NET_ADMIN
    networks:
      extranet:
        ipv4_address: '10.10.163.254'
      dmz:
        ipv4_address: '172.16.163.254'
      intranet:
        ipv4_address: '192.168.163.254'

  #########################################
  #                 DMZ                   #
  #########################################
  web:
    build: ./hosts/web
    image: dath/web:latest
    restart: always
    container_name: dath-web
    cap_add:
      - NET_ADMIN
    networks:
      dmz:
        ipv4_address: '172.16.163.251'
    ports:
      - '2222:22'
      - '8080:80'
      - '4443:443'

  # mail:
  #   build: ./hosts/mail
  #   image: dath/mail:latest
  #   restart: 'no'
  #   container_name: dath-mail
  #   cap_add:
  #     - NET_ADMIN
  #   networks:
  #     dmz:
  #       ipv4_address: '172.16.163.252'

  #########################################
  #               Intranet                #
  #########################################
  dns:
    build: ./hosts/dns
    image: dath/dns:latest
    restart: always
    container_name: dath-dns
    cap_add:
      - NET_ADMIN
    networks:
      intranet:
        ipv4_address: '192.168.163.251'
    ports:
      - '5353:53/udp'
      - '5353:53/tcp'

  dhcp:
    build: ./hosts/dhcp
    image: dath/dhcp:latest
    restart: always
    container_name: dath-dhcp
    cap_add:
      - NET_ADMIN
    networks:
      intranet:
        ipv4_address: '192.168.163.252'
    ports:
      - '6767:67/udp'

  user:
    build: ./hosts/user
    image: dath/user:latest
    restart: always
    container_name: dath-user
    dns: '192.168.163.251'
    cap_add:
      - NET_ADMIN
    networks:
      intranet:
